// Auto-generated by Makefile - DO NOT EDIT MANUALLY
// Generated on: Sun Jul 19 10:32:58 MSK 2026

import Foundation

@available(macOS 13.0, *)
struct BuildInfo {
    static let version = "2026.01"
    static let buildNumber = "1854"
    static let buildDate = "19/07/2026"
    static let codeName = "Albatross"
}
