// Auto-generated by Makefile - DO NOT EDIT MANUALLY
// Generated on: Tue Oct 14 22:57:23 MSK 2025

import Foundation

@available(macOS 13.0, *)
struct BuildInfo {
    static let version = "2026.01"
    static let buildNumber = "1224"
    static let buildDate = "14/10/2025"
    static let codeName = "Albatross"
}
