// Auto-generated by Makefile - DO NOT EDIT MANUALLY
// Generated on: Sun Jul 19 12:19:50 MSK 2026

import Foundation

@available(macOS 13.0, *)
struct BuildInfo {
    static let version = "2026.01"
    static let buildNumber = "1856"
    static let buildDate = "19/07/2026"
    static let codeName = "Albatross"
}
