import SwiftUI

@available(macOS 13.0, *)
struct FSTPAboutView: View {
    // Build information from BuildInfo (generated by Makefile)
    private var buildDate: String {
        return BuildInfo.buildDate
    }

    private var buildNumber: String {
        return BuildInfo.buildNumber
    }

    private var version: String {
        return BuildInfo.version
    }

    private var codeName: String? {
        return BuildInfo.codeName
    }

    var body: some View {
        HStack(spacing: 0) {
            // LEFT PANEL (2/5 width) - Icon + Name + Build + Copyright
            VStack(spacing: 12) {
                Spacer()

                // Application icon
                Image(nsImage: NSApplication.shared.applicationIconImage)
                    .resizable()
                    .frame(width: 128, height: 128)
                    .clipShape(RoundedRectangle(cornerRadius: 20))
                    .shadow(color: Color.black.opacity(0.2), radius: 10, x: 0, y: 5)

                // Application name
                Text("TapeXPlayer")
                    .font(.system(size: 30, weight: .bold))
                    .foregroundColor(.primary)

                // Build information with code name (all in one line)
                if let codeName = codeName {
                    Text("Build \(buildNumber) \"\(codeName)\" (\(buildDate))")
                        .font(.system(size: 8, weight: .semibold))
                        .foregroundColor(.secondary)
                        .padding(.top, 4)
                } else {
                    Text("Build \(buildNumber) (\(buildDate))")
                        .font(.system(size: 8, weight: .semibold))
                        .foregroundColor(.secondary)
                        .padding(.top, 4)
                }

                Spacer()

                // Copyright and license
                VStack(spacing: 6) {
                    Text("© 2025 Maksim Maloletkin (FFB_soffa). Licensed under GPL.")
                        .font(.system(size: 9))
                        .foregroundColor(.secondary)
                        .multilineTextAlignment(.center)

                    // GitHub link
                    Link("github.com/ffbsoffa/TapeXPlayer",
                         destination: URL(string: "https://github.com/ffbsoffa/TapeXPlayer")!)
                        .font(.system(size: 10))
                        .foregroundColor(.blue)

                    // Website link
                    Link("ffbsoffa.org",
                         destination: URL(string: "https://ffbsoffa.org")!)
                        .font(.system(size: 10))
                        .foregroundColor(.blue)
                }
                .padding(.bottom, 20)
            }
            .frame(maxWidth: .infinity)
            .background(Color(NSColor.windowBackgroundColor))

            // RIGHT PANEL (3/5 width) - Library information
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    // Header
                    Text("Third-Party Libraries")
                        .font(.system(size: 16, weight: .bold))
                        .foregroundColor(.primary)
                        .padding(.bottom, 8)

                    // FFmpeg
                    LibraryInfoView(
                        name: "FFmpeg",
                        description: "Video and audio codec library",
                        license: "LGPL v2.1+ / GPL v2+",
                        url: "https://ffmpeg.org"
                    )

                    Divider()

                    // SDL2
                    LibraryInfoView(
                        name: "SDL2",
                        description: "Cross-platform multimedia library",
                        license: "zlib License",
                        url: "https://www.libsdl.org"
                    )

                    Divider()

                    // SDL2_ttf
                    LibraryInfoView(
                        name: "SDL2_ttf",
                        description: "TrueType font rendering library",
                        license: "zlib License",
                        url: "https://github.com/libsdl-org/SDL_ttf"
                    )

                    Divider()

                    // PortAudio
                    LibraryInfoView(
                        name: "PortAudio",
                        description: "Cross-platform audio I/O library",
                        license: "MIT-like License",
                        url: "http://www.portaudio.com"
                    )

                    Divider()

                    // RtMidi
                    LibraryInfoView(
                        name: "RtMidi",
                        description: "Cross-platform MIDI I/O library",
                        license: "MIT-like License",
                        url: "https://github.com/thestk/rtmidi"
                    )

                    Divider()

                    // OpenSSL
                    LibraryInfoView(
                        name: "OpenSSL",
                        description: "Cryptography and SSL/TLS toolkit",
                        license: "Apache License 2.0",
                        url: "https://www.openssl.org"
                    )

                    Divider()
                        .padding(.top, 16)

                    // Apple Frameworks Section
                    Text("Apple Frameworks (macOS)")
                        .font(.system(size: 16, weight: .bold))
                        .foregroundColor(.primary)
                        .padding(.bottom, 8)

                    VStack(alignment: .leading, spacing: 8) {
                        AppleFrameworkView(name: "Cocoa", description: "User interface and application framework")
                        AppleFrameworkView(name: "CoreVideo", description: "Video processing pipeline")
                        AppleFrameworkView(name: "VideoToolbox", description: "Hardware-accelerated video encoding/decoding")
                        AppleFrameworkView(name: "CoreAudio", description: "Low-level audio processing")
                        AppleFrameworkView(name: "CoreMIDI", description: "MIDI device communication")
                        AppleFrameworkView(name: "IOKit", description: "Device and driver access")
                        AppleFrameworkView(name: "QuartzCore", description: "Graphics rendering and animation")
                        AppleFrameworkView(name: "CoreFoundation", description: "Low-level system services")
                        AppleFrameworkView(name: "UniformTypeIdentifiers", description: "File type identification")
                    }
                    .padding(.leading, 8)

                    Text("These frameworks are © Apple Inc. and subject to Apple's Software License Agreement.")
                        .font(.system(size: 9))
                        .foregroundColor(.secondary)
                        .padding(.top, 8)

                    Divider()
                        .padding(.top, 16)

                    // Disclaimer
                    VStack(alignment: .leading, spacing: 6) {
                        Text("This software uses libraries from the FFmpeg project under the LGPLv2.1.")
                            .font(.system(size: 9))
                            .foregroundColor(.secondary)

                        Text("FFmpeg is a trademark of Fabrice Bellard.")
                            .font(.system(size: 9))
                            .foregroundColor(.secondary)

                        Text("All trademarks are property of their respective owners.")
                            .font(.system(size: 9))
                            .foregroundColor(.secondary)
                    }
                    .padding(.top, 8)
                }
                .padding(20)
            }
            .frame(maxWidth: .infinity)
            .background(Color(NSColor.controlBackgroundColor))
        }
        .frame(width: 700, height: 550)
    }
}

// Component for displaying library information
@available(macOS 13.0, *)
struct LibraryInfoView: View {
    let name: String
    let description: String
    let license: String
    let url: String

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(name)
                .font(.system(size: 13, weight: .semibold))
                .foregroundColor(.primary)

            Text(description)
                .font(.system(size: 11))
                .foregroundColor(.secondary)

            HStack(spacing: 4) {
                Text("License:")
                    .font(.system(size: 10, weight: .medium))
                    .foregroundColor(.secondary)

                Text(license)
                    .font(.system(size: 10))
                    .foregroundColor(.secondary)
            }

            Link(url, destination: URL(string: url)!)
                .font(.system(size: 10))
                .foregroundColor(.blue)
        }
    }
}

// Component for displaying Apple framework
@available(macOS 13.0, *)
struct AppleFrameworkView: View {
    let name: String
    let description: String

    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: "apple.logo")
                .font(.system(size: 11))
                .foregroundColor(.secondary)
                .frame(width: 16)

            VStack(alignment: .leading, spacing: 2) {
                Text(name)
                    .font(.system(size: 11, weight: .medium))
                    .foregroundColor(.primary)

                Text(description)
                    .font(.system(size: 10))
                    .foregroundColor(.secondary)
            }
        }
    }
}

// Wrapper for showing About window
@available(macOS 13.0, *)
class FSTPAboutWindowController: NSWindowController {
    convenience init() {
        let hostingController = NSHostingController(rootView: FSTPAboutView())
        let window = NSWindow(contentViewController: hostingController)
        window.title = "About TapeXPlayer"
        window.styleMask = [.titled, .closable]
        window.isReleasedWhenClosed = false
        window.center()

        self.init(window: window)
    }
}

// Global variable to store About window
private var aboutWindowController: NSWindowController?

// Function to show About window (called from Objective-C)
@available(macOS 13.0, *)
@_cdecl("ShowSwiftUIAboutWindow")
public func ShowSwiftUIAboutWindow() {
    // Always recreate window to ensure BuildInfo is up to date
    // (BuildInfo.swift is regenerated on each build)
    aboutWindowController = FSTPAboutWindowController()

    aboutWindowController?.showWindow(nil)
    NSApp.activate(ignoringOtherApps: true)
}
