#pragma once

// Auto-generated by Makefile - DO NOT EDIT MANUALLY
// Generated on: Sun Jul 19 12:19:50 MSK 2026

#define TAPEXPLAYER_VERSION "2026.01"
#define TAPEXPLAYER_CODE_NAME "Albatross"
#define TAPEXPLAYER_BUILD_NUMBER "1856"
#define TAPEXPLAYER_BUILD_DATE __DATE__

// Helper functions
inline const char* GetTapeXPlayerVersion() { return TAPEXPLAYER_VERSION; }
inline const char* GetTapeXPlayerCodeName() { return TAPEXPLAYER_CODE_NAME; }
inline const char* GetTapeXPlayerBuildNumber() { return TAPEXPLAYER_BUILD_NUMBER; }
inline const char* GetTapeXPlayerBuildDate() { return TAPEXPLAYER_BUILD_DATE; }
