name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd source
          pacman -S mingw-w64-x86_64-gcc
          pacman -S mingw-w64-x86_64-SDL2
          pacman -S mingw-w64-x86_64-portaudio   
          make clean
          make
