name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: make
      run: /source/make clean
    - name: make check
      run: /source/make 
